### ISSUE TITLE
com.sap.cloud.sdk.cloudplatform.connectivity.exception.DestinationNotFoundException

### ISSUE THREAD

**Issue by Anik-SAP** [SAP/cloud-sdk-java#267]
### Issue Description

 - We have a destination named “CC8_BP”. While the destination responds correctly when called synchronously, we are facing an error when attempting asynchronous calls through background threads. The error message we are receiving is as follows: " **Failed to fetch configuration for destination CC8_BP during action execution: com.sap.cloud.sdk.cloudplatform.connectivity.exception.DestinationNotFoundException: Destination could not be found in any of the registered loaders. Check the suppressed exceptions and the logs above to see which loaders where queried.**"
This is happening for all the destinations, CC8_BP is used as an example here.

- Application is multi-tenant.
- Destinations are on the subscriber account.

Important information:
- Expected outcome: Successfully getting the response without the "Destination not found" error.
- Actual outcome: Failed to fetch configuration for destination CC8_BP during action execution: com.sap.cloud.sdk.cloudplatform.connectivity.exception.DestinationNotFoundException: Destination could not be found in any of the registered loaders. Check the suppressed exceptions and the logs above to see which loaders where queried..

### Impact / Priority

 
Affected development phase: Development.
 
Impact: Blocked

Timeline: takt 01.2024

## Error Message

```
Failed to fetch configuration for destination CC8_BP during action execution: com.sap.cloud.sdk.cloudplatform.connectivity.exception.DestinationNotFoundException: Destination could not be found in any of the registered loaders. Check the suppressed exceptions and the logs above to see which loaders where queried.
```

## Project Details

* SDK Version: <4.29.0>

* Link to GitHub repo: <https://github.tools.sap/AP-AC-Products-Services/Actions>
* Project type, for example:
    * [ ] CAP Project
    * [x] SDK Maven Archetype
    * [ ] None of the above:
* Platform:
    * [x] Cloud Foundry
    * [ ] Deploy with Confidence (Cloud Foundry)
    * [ ] None of the above:

-----

### Checklist

- [x] Checked out the [documentation](https://sap.github.io/cloud-sdk/docs/java/sdk-java-troubleshooting-frequent-problems) and [Stack Overflow](https://stackoverflow.com/questions/tagged/sap-cloud-sdk)
- [x] Description provided with all relevant information
- [x] Exception and stack trace provided
- [ ] Attached debug logs
- [ ] Attached dependency tree
- [x] Provided Cloud SDK version & link to relevant source code

**Comment by newtork** [comment]
Hello @Anik-SAP,

I can't really tell from your project `main` branch where exactly this exception is originating from.
But usually when multitenancy works synchronously but not asynchronously, this is due to our `ThreadContext` not being propagated correctly. Depending on the API which is used for asynchronous operation, this can be solved in different ways
* There's the option to define a [custom `AsyncConfigurer`](https://sap.github.io/cloud-sdk/docs/java/features/multi-tenancy/thread-context#spring-integration) which enables support for `@Async` marked methods.
* Since you already have [the Spring related annotations present](https://sap.github.io/cloud-sdk/docs/java/features/multi-tenancy/thread-context#how-is-a-thread-context-created), this would work for methods wrapped in [Resilience API](https://sap.github.io/cloud-sdk/docs/java/features/resilience) and [Accessor API](https://sap.github.io/cloud-sdk/docs/java/features/multi-tenancy/thread-context#how-can-the-thread-context-be-used).
* Instead of propagating, it's also possible to create [a new `ThreadContext` based on request headers](https://sap.github.io/cloud-sdk/docs/java/features/multi-tenancy/thread-context#create-a-new-requestheadercontainer-from-scratch), which may be useful for scheduled operations, detached from a request context.

Kind regards
Alexander

(Disclaimer: this is a publicly visible issue)

**Comment by Anik-SAP** [comment]
Hello @newtork ,

We were actually using **SimpleAsyncTaskExecutor** and not **ThreadContextExecutors.** 
 
```
@Override
public Executor getAsyncExecutor() {
    final SimpleAsyncTaskExecutor executor = new SimpleAsyncTaskExecutor();
    executor.setThreadNamePrefix("AsyncThread-");
    return executor;
}
```
 
Can you please help us know the difference between SimpleAsyncTaskExecutor and ThreadContextExecutors for better understanding as **now it is working after using ThreadContextExecutors class**.

Thanks & Regards
Anik Das

**Comment by newtork** [comment]
Your project returns an instance of `TaskExecutor extends Executor` for `AsyncConfigurer`.
Unfortunately this is not compatible with our API, since we expect an `ExecutorService extends Executor`.

Therefore I can only suggest to use the Spring based header injection and creating a new context for _SAP Cloud SDK_, like this:

```java
void doThing( @RequestHeader final HttpHeaders headers )
{
  final RequestHeaderContainer container = DefaultRequestHeaderContainer.fromMultiValueMap(headers);
  RequestHeaderAccessor.executeWithHeaderContainer(container, () -> {
      // test of logic that contains destination handling
  });
}
```

**Comment by Anik-SAP** [comment]
Thanks a lot for helping out with the issue. Closing it as the issue has been resolved successfully.

**Comment by jjtang1985** [comment]
Notes: `TaskExecutor` is a spring based interface.
