### ISSUE TITLE
Question: Change set between different API URLs

### ISSUE THREAD

**Issue by lhozdroid** [SAP/cloud-sdk-java#429]
**Just asking a question, this is not an issue or bug**
Is there any way that calls between different API URLs be linked in a change set?  For instance do a call in a change set for API_PHYSICAL_DOC_SRV and API_BILL_OF_MATERIAL_SRV together in a single call? Might be asking too much but just out of curiosity.
Thanks in advance for the help.

**Comment by Johannes-Schneider** [comment]
Hi @lhozdroid,

as to my knowledge, such as a scenario is not possible.

This is because two different API URIs would indicate the usage of two different, logically (and physically) separated OData services.
The OData specification describes the expected behavior of a **single** service, implicitly assuming that each service is entirely self-contained.
Therefore, cross-service consumption scenarios, AFAIK, are not covered by the official specification and, therefore, would require some custom implementation that would be (highly) specific to the providing vendor.

So even if there are such custom implementations, we (the SAP Cloud SDK) would not support them as we are trying to stick to the official OData specification as closely as possible.

Hope that helps.

Best regards,
Johannes

**Comment by Johannes-Schneider** [comment]
Hi @lhozdroid,

yes, you can indeed first create and then later (in the same change set) reference the (potentially) created entity to do further modifications.

Here are the corresponding specifications:

- [OData v2](https://www.odata.org/documentation/odata-version-2-0/batch-processing/) (Section `2.2.1`)
- [OData v4](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#_Toc31359026) (Section `11.7.7.2`)

I fear, though, that the SAP Cloud SDK currently has no type-safe support for such scenarios.
But I'm also checking with a colleague who is more familiar with our client implementation, so take my statement with a grain of salt for the moment.

Best regards,
Johannes

**Comment by lhozdroid** [comment]
Hi,

Thank you very much for the answer.  I really appreciate all the help.

Best regards.
