### ISSUE TITLE
Missing replacement for ScpCfAuthTokenFacade when upgrade from version4 to version5

### ISSUE THREAD

**Issue by sap-real-estate** [SAP/cloud-sdk-java#468]
As mentioned in https://github.wdf.sap.corp/MA/sdk/issues/8763, we are current migrating from v4 to v5, however in v4 we were extending ScpCfAuthTokenFacade class, however when I unfolded section from [your migration guide](https://sap.github.io/cloud-sdk/docs/java/guides/5.0-upgrade-steps#remove-or-replace-modified-sap-cloud-sdk-apis), there is no description about whether they are removed or replaced.

**Comment by sap-real-estate** [comment]
One other class `LocalScopePrefixProvider`, in your documentation it says for this class there is no replacement, what does it mean? It means we should not use it anymore?

**Comment by newtork** [comment]
> in v4 we were extending `ScpCfAuthTokenFacade` class

We don't have this documented, likely because this is some special overloading/customization of base-classes. Although it is a `public`, non-final, unsealed class - usually you would implement an `interface` instead of extending a platform-specific base-class.

You could use [`DefaultAuthTokenFacade`](https://github.com/SAP/cloud-sdk-java/blob/main/cloudplatform/security/src/main/java/com/sap/cloud/sdk/cloudplatform/security/DefaultAuthTokenFacade.java) instead. We migrated the original code to this new class.


> One other class `LocalScopePrefixProvider`, in your documentation it says for this class there is no replacement, what does it mean?

_SAP Cloud SDK_ no longer validates auth tokens from incoming web requests. Therefore any logic to parse the token is no longer available. However since `AuthToken#getJwt()` returns a [`DecodedJWT`](https://www.javadoc.io/doc/com.auth0/java-jwt/3.3.0/com/auth0/jwt/interfaces/DecodedJWT.html), you can easily extract any data provided.

> It means we should not use it anymore?

If you used the API before to extract scope information from the provided JWT, then **yes** you need to change your code and extract it yourself.
