### ISSUE TITLE
SDK 5.13.0, connectivity-apache-httpclient5, depends on apache httpclient5 5.4

### ISSUE THREAD

**Issue by hdva2502** [SAP/cloud-sdk-java#602]
Hi colleagues,

with the update from 5.12.0 => 5.13.0, the connectivity-apache-httpclient5 depends on apache httpclient5 5.4.

However, the SAP Java Buildpack sap_java_buildpack_jakarta_2_18 which is currently the latest one 
https://mvnrepository.com/artifact/com.sap.cloud.sjb.cf/sap-java-buildpack-bom/2.18.0
available on SAP BTP factory landscapes, contains only 5.3.1

Please have a look.

Thanks,
Andreas

**Comment by MatKuhr** [comment]
Thanks for reporting this! 

As discussed over teams: The Cloud SDK is not kept in sync with the SAP Java Buildpack or the SAP SGS provided BOMs. So for now leaving the Cloud SDK version at 5.12.0 would be needed (due to [these changes](https://github.com/SAP/cloud-sdk-java/commit/d407451352dc41edec862764abfb5bcef525b280) that happened with the upgrade to http client 5.4), until SJB and SGS update.
