### ISSUE TITLE
When I send a GET request to ODATA using SAP Cloud SDK in SAP Business Application Studio, an empty object is returned

### ISSUE THREAD

**Issue by absmh** [SAP/cloud-sdk-java#650]
**Issue Description**
In SAP Business Application Studio, I am developing a Java program that uses SAP Cloud SDK to send a GET request to ODATA to retrieve data.
When executing a GET request, some ODATA successfully retrieves data, but there is an issue where an empty object is returned for some ODATA.
Even if an empty object is returned, no error occurs and the program ends normally.
In addition, when executing a request with the SAP standard transaction code "/n/IWFND/GW_CLIENT" or Postman for the problematic ODATA, data can be retrieved without any problems. Data cannot be retrieved only when calling from SAP Business Application Studio.

Has there been any confirmed occurrence of such an issue to date?
*Due to confidentiality reasons, I cannot share the details of the project, so I am providing the minimum information possible to start with. I will add more information as necessary.

**Supplementary Information**
--ODATA for which data cannot be obtained:
1)ODATA：API_PRODUCT_SRV
　Entity：A_ProductPlant、A_ProductStorageLocation、A_ProductValuation
2)ODATA：API_COSTCENTER_SRV
　Entity：A_Costcenter
3)ODATA：API_MATERIAL_STOCK_SRV
　Entity：A_MatlStkInAcctMod
4)ODATA：API_GLACCOUNTINCHARTOFACCOUNTS_SRV
　Entity：A_GLAccountText

--Sample source code:
Here is the source code to execute a GET request on API_PRODUCT_SRV.A_ProductStorageLocation.

```
private static final HttpDestination destination = DestinationAccessor.getDestination("destination name").asHttp();
private static final DefaultProductSrvService service = new DefaultProductSrvService().withServicePath("service path");
final List<StorageLocationData> result = service.getAllProductStorageLocation().executeRequest(destination);
```

--SDK version: <5.14.0>
--Project type: MTA project
--Development environment: SAP Business Application Studio

**Comment by KavithaSiva** [comment]
Hi @absmh,

Are you trying to access the OData service on an on-premise system or a Cloud system?
Could you please cross-check with this [guide](https://sap.github.io/cloud-sdk/docs/js/guides/bas#case-2-connection-to-cloud-systems), to see if your set up with Business Application Studio is right?

The code snippet looks good to me, so if there is an issue while retrieving data you should ideally get an `ODataException`.
Do you have any additional code in a `catch` block to return gracefully in case of failures?

Would it be possible to get debug logs or debug your application to see what exactly happens? And if the OData service itself is returning these empty results?

Regards,
Kavitha

**Comment by absmh** [comment]
Hi @KavithaSiva ,
Sorry for the late reply. Thank you for your comment.

I am trying to access an OData service on an on-premise system.

I checked the guide and there seemed to be no problem with the Business Application Studio setup.

I omitted this in the source code I provided, but the part where the data is retrieved is surrounded by a try-catch so that the ODataException can be caught. There is also an outer try-catch so that other exceptions can be caught.
However, when I run the program, no exceptions occur and it ends normally, so I cannot find out what is wrong.

```
try{
	・・・
	try{
		final List<StorageLocationData> result = service.getAllProductStorageLocation().executeRequest(destination);
	}catch(ODataException e){
                //Outputting logs
		throw new ODataException(e);
	}
	・・・
}catch(Exception e){
         //Outputting logs
	throw new Exception(e);
}
```
If the code snippet is correct, are there any other possible causes? If there are any points that I should pay attention to, such as environment settings or permission settings, I would appreciate it if you could let me know.

Thank you,

**Comment by newtork** [comment]
* We do have a short [BAS section in the Java docs](https://sap.github.io/cloud-sdk/docs/java/features/connectivity/running-locally#on-premise-connectivity-from-business-application-studio-bas) too. However since your request succeeds without exception, our concerns regarding the connectivity seem unproductive for your case. Your concern is empty OData payload, if I understood correctly.

* While you have a static OData service instance, that's fine, we strongly discourage users to declare destinations statically. While the former is (almost) stateless, the latter has temporary state. Letting destinations live for eternity may lead to authentication tokens aging and worst case disabling multi-tenancy. _SAP Cloud SDK_ has an effective caching logic, that encourages users to always resolve destinations via `DestinationAccessor` everytime at runtime. There should not be any drawbacks.

* If the response object in Java code differs from your manual REST client request (e.g. Postman), then something is different with the request parameters. I would suggest to temporary enable HTTP wirelogs. Just for the duration of your investigation, you can set log level: `org.apache.http=DEBUG`, this will show all traffic for your application. Hopefully you'll find the affected request and compare the traffic with your REST client call.
