### ISSUE TITLE
 Sanitation of URL via ODataUriFactory

### ISSUE THREAD

**Issue by AmnaNizarHussain** [SAP/cloud-sdk-java#99]
## Issue Description
I’ve come across a doubt while implementing some changes for migrating to Cloud SDK.
 
I tried to implement the creation of a URL using the ODataRequestRead class with the base URL example as below:
 
Base URL : https://sap1.fgvms.com/api/vc
 
The ODataRequestRead class is used for creating the request as shown below :
 
ODataRequestRead request = new ODataRequestRead(baseUrl, structuredQuery.getEntityOrPropertyName(), queryString, ODataProtocol.V2);
(The ‘queryString’ has been created using StructuredQuery class)
 
After creating the request like above, we do a REST template call to hit the URL. We are facing a problem in this part.
If we try getting the request URI from the above created request using the method - request1.getRelativeUri() , some sanitation of URL happens and we get a malformed URL as such :
 
/https:/sap1.fgvms.com/…
 
Even though the base URL has the “https” part correctly, relative URI from the ODataRequestRead request gives out a different URI with the “https” part altered.
I tried debugging and found that a piece of code in ODataUriFactory does some sanitation to the URL :
![image](https://github.com/SAP/cloud-sdk-java/assets/85312527/8f241956-a340-4342-be56-24a55c9a1818)

### Impact / Priority

 
It is affecting our productive code.

```

<!-- Application Logs
Please make sure you [set your log level to debug](https://sap.github.io/cloud-sdk/docs/java/guides/logging-overview#configuring-logback) and attach the resulting log output as .txt or .log file to this issue.
This is _very important_ as it usually gives a lot of information that is necessary to get to the root cause of an issue. Be sure to redact confidential information before posting.
-->

<!-- Maven Dependency Tree
Please attach the Maven dependency tree of your project. You can obtain that by running "mvn dependency:tree" on the command line. Kindly note that you could have several pom.xml files in your project.
If so, please provide the dependency tree for the pom.xml of the root module and the module named like `application´ or `srv` that contains the application logic.
-->

## Project Details

<!--
Please provide as much information about your project as possible.
If you cannot share your project for confidentiality reasons, please consider providing a minimal working example https://en.wikipedia.org/w/index.php?title=Minimal_working_example&oldid=893866607
-->

* SDK Version: <your SAP Cloud SDK version here>
<!-- The group id of the modules of the SAP Cloud SDK start with "com.sap.cloud.sdk" -->
* Link to GitHub repo: <your link here>
* Project type, for example:
    * [ ] CAP Project
    * [ ] SDK Maven Archetype
    * [ ] None of the above:
* Platform:
    * [ ] Cloud Foundry
    * [ ] Deploy with Confidence (Cloud Foundry)
    * [ ] None of the above:

-----

### Checklist

- [ ] Checked out the [documentation](https://sap.github.io/cloud-sdk/docs/java/sdk-java-troubleshooting-frequent-problems) and [Stack Overflow](https://stackoverflow.com/questions/tagged/sap-cloud-sdk)
- [ ] Description provided with all relevant information
- [ ] Exception and stack trace provided
- [ ] Attached debug logs
- [ ] Attached dependency tree
- [ ] Provided Cloud SDK version & link to relevant source code

**Comment by newtork** [comment]
Hi @AmnaNizarHussain,

You are using the [Generic OData Client](https://sap.github.io/cloud-sdk/docs/java/features/odata/generic-untyped-odata-client), which we also call **expert API** and we usually don't advertise it to our users. That means the following:
* for some cases, as a developer you would need expert knowledge - or carefully read the JavaDoc
* API convenience is not in focus
* not all edge-cases are considered

---

In your case, please find the correct parameters:

```java
  public ODataRequestRead(
     @Nonnull final String servicePath,
     @Nonnull final String entityName,
     @Nullable final String encodedQuery,
     @Nonnull final ODataProtocol protocol )
```
First argument is a relative or absolute **path**. 

While the `execute(HttpClient)` method assumes a generic `HttpClient` object according to API, internally we require it to come from `HttpClientAccessor.getHttpClient(HttpDestination)`. We're extracting the server address (hostname) from the provided destination. [Destination API](https://sap.github.io/cloud-sdk/docs/java/features/connectivity/destination-service) is one of our central concepts in SAP Cloud SDK.

Code suggestion:

```diff
  ODataRequestRead request = new ODataRequestRead(
-   "http://foo/bar", [...]
+   "/bar", [...]

  HttpClient httpClient =
-   HttpClient.newBuilder().build();
+   HttpClientAccessor.getHttpClient(DefaultHttpDestination.builder("http://foo").build());

  request.execute(httpClient);
```

However I would recommend to checkout the convenience API for OData v2/v4 instead of using the expert API:
https://sap.github.io/cloud-sdk/docs/java/features/odata/overview

But use whatever works best for you :+1:

Kind regards
Alexander

**Comment by cschubertcs** [comment]
I will close this issue, as there was no update since two weeks here anymore.

If you still have questions, feel free to raise another issuer or re-open this one.
